### ISSUE TITLE
Dead link to knowledge base

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#17]
The knowledge base link in the footer directs to https://nfdi4plants.org/content/docs/research-data-management.html, which does not exist any more (was changed to https://nfdi4plants.org/content/docs/ResearchDataManagement.html...). 

Maybe implement a knowledge base landing page and link to that.

**Comment by Freymaurer** [comment]
> Maybe implement a knowledge base landing page and link to that.

@CMR248

**Comment by Brilator** [comment]
I would suggest to create one single page where the visitor is redirected to when clicking "Knowledge Base" in the Navbar. 
Just with a few lines introducing what the KB is, incl. sidebar on the left. 

Would it make sense to create a new `layout: landing` for this? 

  - no (i.e. ignore) date / published, author, etc.
  - MAY contain TOC
  - MAY contain sidebar

**Comment by Freymaurer** [comment]
Would it be possible to just imitate the design of `web-component-docs`? Some documentation repos just start with an `Home`/`Index` page.

- https://nfdi4plants.github.io/web-components-docs/
- https://safe-stack.github.io/docs/

**Comment by Brilator** [comment]
Yes, that's perfectly enough. It's really just to have a save and persistent link to the kb.

My suggestion for the landing page (not PR'ed to main, yet): 
https://github.com/Brilator/nfdi4plants.github.io/blob/main/src/content/docs/landings/landing_knowledgebase.md

**Comment by Freymaurer** [comment]
It would be awesome if those bold textparts could be actual links to the corresponding subpages!

For a consisting naming, could you change the .md file name to either `index.md` or `home.md`?

**Comment by Brilator** [comment]
> It would be awesome if those bold textparts could be actual links to the corresponding subpages!

Yes, but then it gets more complicated for you -> would require additional sub-landing pages for the sections. At the moment those are just drop-down menus.

**Comment by Brilator** [comment]
> For a consisting naming, could you change the .md file name to either index.md or home.md?

Sure

**Comment by Freymaurer** [comment]
> Yes, but then it gets more complicated for you -> would require additional sub-landing pages for the sections. At the moment those are just drop-down menus.

Index pages for sub-categories should not be any different to all other .md files and do not require specific parsing.

See at the example of [web-component-docs](https://nfdi4plants.github.io/web-components-docs/):

- index-url = `https://nfdi4plants.github.io/web-components-docs/`
  - no .html referenced
- further sub-category landing pages (if wanted), would be `https://nfdi4plants.github.io/web-components-docs/` + `subcategory` + `home.md/index.md/introduction.md`. Which can be created/referenced, etc just as all other .md files.

**Comment by Brilator** [comment]
I understand, I was just trying to say that, the section "heading" itself isn't linked. 


![Screen Shot 2022-07-07 at 10 10 13](https://user-images.githubusercontent.com/16229676/177724759-bd55468e-2727-4d47-88be-20e220d8fc31.png)

orange arrows: no link 
blue arrows: link 

So, this comes with redundancy (2x "Web Components", 2x "Development") and another level.

**Comment by Freymaurer** [comment]
Yeah, i imagine it to look something like this for the knowledgebase:

![image](https://user-images.githubusercontent.com/39732517/177725580-700c0572-3d58-4213-a723-84b24c2160ca.png)

**Comment by Brilator** [comment]
Fine for me.

**Comment by CMR248** [comment]
Looks good to me too. It would be great if the outsourced repo could be edited by @Martin-Kuhl, being the main responsible for the KB. So he should at least be lited as maintainer.
