### ISSUE TITLE
Headline "&" not rendering properly in TOC

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#18]
The "&" in one article headline does not properly render in the TOC. 

<img width="512" alt="Screen Shot 2022-06-23 at 15 11 23" src="https://user-images.githubusercontent.com/16229676/175307090-4b1c51e2-037b-449f-8059-73d1f24ca23c.png">

article: https://github.com/nfdi4plants/nfdi4plants.github.io/blob/main/src/content/docs/AnnotatedResearchContext.md
line 54

**Comment by Freymaurer** [comment]
Fixed and should update tonight ~23:00 👍

**Comment by Freymaurer** [comment]
Should be fixed now! Thanks for taking the time to report this issue! 

https://nfdi4plants.org/content/docs/AnnotatedResearchContext.html
