### ISSUE TITLE
Allow structuring docs articles in sub-directories. 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#20]
To structure content in the knowledge base, let web-components parse .md`s in subdirectories. 

I would suggest: 

(src/docs)/fundamentals -> articles on RDM and FAIR fundamentals
(src/docs)/implementation -> articles on tools and how we implement FAIR RDM in DataPLANT
(src/docs)/tutorials -> training materials and smaller tutorials

**Comment by Brilator** [comment]
@Freymaurer

**Comment by Freymaurer** [comment]
I will try to do the parsing with an exclusion list. Like "parse all subfolders, except `sidebars` and ignore all files, named `README.md`.

**Comment by Brilator** [comment]
Sounds good. Would also be more flexible in case we need to change. 

I added a note that fornax will try to parse (and fail if yaml missing) any md in the docs (except README.md).

**Comment by Freymaurer** [comment]
Handled according to https://github.com/nfdi4plants/nfdi4plants.knowledgebase/tree/main/src#markdown-to-html-rendering-rules
