### ISSUE TITLE
Layout: sidebar?

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#21]
Would it make sense to add a `layout: sidebar`? 
Without any yaml metadata parsed.

**Comment by Freymaurer** [comment]
What would you like to happen if something has `layout: sidebar`?

**Comment by Brilator** [comment]
Let it render to a sidebar. 
Was just an idea to more concisely handle sidebar.md files, rather than pulling from a specific folder.

**Comment by Freymaurer** [comment]
The underlying fornax logic uses layout to parse markdown into html documents. The sidebars are never standalone html documents, but are subparts of other layouts. Changing this behaviour would not only go against the fornax logic, but would also introduce plenty of room for bugs. In this case i would advice against this change and close the issue for now.
If you disagree feel free to comment on this issue, then we can go into a deeper discussion.
