### ISSUE TITLE
Change "published" to "date" in yaml block

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#22]
1. Things may be created, but not "visibly" published
2. Other .md parsers use `date` by default, in case we want to export to pdf.

**Comment by Freymaurer** [comment]
I could do `date/published`, so both would work. This way the old one would not directly result in an error.

**Comment by Brilator** [comment]
Would having both break it? Or whatever comes last is used?

**Comment by Freymaurer** [comment]
Having both would be exactly an `OR` case. So when looking for the date i would search for `date` **OR** `published`, if one of those exists is uses the value, if none exisist it would error, if both exist it would take the one i ask for first or the one coming first (depending on how i implement it).

**Comment by Freymaurer** [comment]
Done! 🎉
