### ISSUE TITLE
[Bug] out-commenting in sidebar

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#24]
Spotted a weird behavior, when trying to out-comment sections (under development) in the sidebar. 

![Screen Shot 2022-07-07 at 10 06 48](https://user-images.githubusercontent.com/16229676/177724207-698710c1-bb86-4920-a1f8-f3c9423b309d.png)

**Comment by Freymaurer** [comment]
I don't fully get what the weird behaviour exactly is. Maybe you could point me to it more directly 😄

**Comment by Brilator** [comment]
Cannot reproduce the error anymore. 
When out-commenting a complete block in the sidebar (not line by line), no content would be rendered to html anymore.
