### ISSUE TITLE
[minor bug] support block

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#26]
Two small issues with the bottom support block: 

1. Header: "Dataplant" -> "DataPLANT"
2. There's a space after "directly"

![Screen Shot 2022-09-23 at 11 19 21](https://user-images.githubusercontent.com/16229676/191930072-4cd6907b-a3b1-48ca-a349-47f5f429385e.png)

**Comment by Freymaurer** [comment]
Will be changed on tuesday ~23pm!
