### ISSUE TITLE
[minor] dynamic window size

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#28]
Any chance to adapt the width of how articles + sidebar are shown? 
On bigger (than laptop) displays there's a lot of un-used space left and right in the browser making the articles appear longer (less appealing) to read.

**Comment by Freymaurer** [comment]
The article is already wider then optimal. There are multiple online sources talking about optimal "word count" or "character count" per line for readability.

https://baymard.com/blog/line-length-readability
https://kickpoint.ca/the-readability-formula-making-your-website-easy-to-read/

In our case we already have around ~90 characters per line.

If you are adamant about this change i would recommend bringing this up in the next tools(?) meeting?

**Comment by Brilator** [comment]
Fair point.
