### ISSUE TITLE
allow html / or markdown type emojis in sidebar

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#31]
This would be helpful to visibly highlight materials (walk-throughs, tutorials, QuickStarts) for users.

**Comment by Freymaurer** [comment]
This already works 

https://emojipedia.org/sparkles/

![image](https://user-images.githubusercontent.com/39732517/207904854-b43f8858-160d-4d5a-bf68-c0bda277a9d9.png)

![image](https://user-images.githubusercontent.com/39732517/207904892-641d67d5-e293-423e-9737-8604304198aa.png)

![image](https://user-images.githubusercontent.com/39732517/207904926-73e05db4-a070-4a55-a1c7-5dc66e9a79ba.png)
