### ISSUE TITLE
ugly table display in Safari

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/web-components#37]
<img width="1001" alt="Screenshot 2023-05-12 at 08 05 48" src="https://github.com/nfdi4plants/web-components/assets/16229676/91a9a157-9d74-490c-bdfb-819592bb5653">

This is a screenshot of https://nfdi4plants.org/nfdi4plants.knowledgebase/docs/fundamentals/ResearchDataManagement.html (production). 

Not sure, if solved with updated fornax / web-components. At least I don't have the issue in my updated fork while in watch mode.

**Comment by Brilator** [comment]
> Not sure, if solved with updated fornax / web-components. At least I don't have the issue in my updated fork while in watch mode.

Unfortunately not. It's still there after yesterday's update.

**Comment by Freymaurer** [comment]
Can you check (via rightclick & insepect) where the red border originates from?

**Comment by Freymaurer** [comment]
nevermind found it, was a leftover from development 😅
